apiVersion: v1
kind: Service

metadata:
  name: enterprise-app
  namespace: enterprise-dev

spec:
  type: ClusterIP

  selector:
    app: enterprise-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
